load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "95452dfa7e3782721c7235e56abf56e624872e0f9e11b1a59d0a04082413df8f",
    strip_prefix = "rules_jvm_external-eec0b9c5e7e95d58ae9857e78e2475a89a7d6033",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/eec0b9c5e7e95d58ae9857e78e2475a89a7d6033.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.0-jre",
        "junit:junit:4.13.1",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
