load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "baa8a9729f12fc443c2aeca11e64511470dd6b9292ee3f35cf068ab7d0f1793c",
    strip_prefix = "rules_jvm_external-5d266dd75c4677aeb86ea6c0b23542c114689362",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/5d266dd75c4677aeb86ea6c0b23542c114689362.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.0-jre",
        "junit:junit:4.13.1",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
